/** OpenClaw OS capability kernel. Discovery facades are inert and share one full-mode runtime. */
import type { IncomingMessage, ServerResponse } from "node:http";
import { randomBytes } from "node:crypto";
import { join } from "node:path";
import type { ApprovalQueue, DryRunResult, GatekeeperSession, Grant, ToolResult } from "@clawos/shared";
import { evaluateInstall, ApprovalDecisionParams, ConnectGatekeeperParams, IntroduceParams, ListGrantsParams, RevokeGrantParams } from "@clawos/shared";
import { Type, type TSchema } from "typebox";
import { Value } from "typebox/value";
import type { GatewayMethodOptions, HookCtx, HookEvent, OpenClawPluginApi, OpenClawPluginServiceContext, PluginTrustedToolPolicyRegistration } from "./upstream/sdk.js";
import { createPluginRuntimeStore } from "./upstream/sdk.js";
import { Store } from "./store.js";
import { Registry, instanceId } from "./registry.js";
import { AuditLog } from "./audit.js";
import { ApprovalQueueImpl } from "./approvals.js";
import { osPaths } from "./upstream/paths.js";
interface CallStash{agentId:string;sessionKey:string;runId?:string;session?:GatekeeperSession;queue?:ApprovalQueue;grant?:Grant;tool?:string;paramsJson?:string;expiresAt:number;startedAt:number;}
interface Runtime{store:Store;registry:Registry;audit:AuditLog;approvals:ApprovalQueueImpl;stash:Map<string,CallStash>;inflight:Map<string,CallStash>;notes:Map<string,string[]>;sessions:Map<string,Map<GatekeeperSession,string>>;}
type GatewayMethod=(opts:GatewayMethodOptions)=>Promise<void>|void;
const slot=createPluginRuntimeStore<Runtime>({pluginId:"clawos-kernel",errorMessage:"Kernel unavailable."});
const text=(value:string)=>({content:[{type:"text" as const,text:value}],details:{}});
const EmptyParams=Type.Object({},{additionalProperties:false});
const AuditQueryParams=Type.Object({limit:Type.Optional(Type.Integer({minimum:1,maximum:1000}))},{additionalProperties:false});

export class Kernel{
  readonly paths=osPaths();
  private readonly catalog=new Registry(process.env.CLAWOS_GATEKEEPER_CATALOG??join(this.paths.os,"gatekeepers.json"),this.paths.stateDir);
  constructor(private readonly api:OpenClawPluginApi){}
  async start():Promise<void>{if(slot.tryGetRuntime())throw new Error("Kernel runtime already started.");const store=new Store(this.paths.sqlite);store.migrate();const audit=new AuditLog(this.paths.auditDir);slot.setRuntime({store,registry:this.catalog,audit,approvals:new ApprovalQueueImpl(store,audit,cell()),stash:new Map(),inflight:new Map(),notes:new Map(),sessions:new Map()});}
  async stop():Promise<void>{const r=slot.tryGetRuntime();if(!r)return;for(const sessions of r.sessions.values())for(const session of sessions.keys())await session.close().catch(()=>{});await r.audit.flush();r.store.close();if(slot.tryGetRuntime()===r)slot.clearRuntime();}
  private runtime():Runtime{return slot.getRuntime();}
  private config(){return(this.api.pluginConfig??{})as{operators?:Array<{channel:string;senderId:string}>;maintenance?:boolean;egress?:{denyPatterns?:string[]};install?:{allowSources?:string[];allowHashes?:string[]}};}
  private operator(channel:string|undefined,sender:string|undefined){return!!channel&&!!sender&&this.config().operators?.some(x=>x.channel===channel&&x.senderId===sender)===true;}
  async resolveGrant(agentId:string,sessionKey:string,handle:string){const r=this.runtime(),candidate=r.store.getGrant(handle),grant=candidate&&r.store.authorizeGrant(candidate,agentId,sessionKey,cell());if(!grant)throw new Error("No such grant.");if(grant.audience==="owner-only"&&r.store.observers(sessionKey).length)throw new Error("Grant unavailable for this audience.");const queue=r.approvals.forGrant(grant,sessionKey);const opened={...await r.registry.openSession(grant,queue),queue};r.store.upsertInstance({id:opened.instanceId,vendor:grant.vendor,resourceKey:grant.resourceKey,operatorId:grant.operatorId,observerStrategy:r.registry.entries.get(grant.vendor)?.resources.find(x=>x.type===grant.resourceType)?.observerStrategy??"private-only",lockdown:0});let sessions=r.sessions.get(sessionKey);if(!sessions){sessions=new Map();r.sessions.set(sessionKey,sessions);}sessions.set(opened.session,grant.handle);return{grant,...opened};}
  capabilityPolicy():PluginTrustedToolPolicyRegistration{return{id:"clawos-capability-policy",description:"Deny gatekeeper calls without an active capability.",...(this.catalog.toolNames().length?{matcher:this.catalog.toolNames()as[string,...string[]]}:{}),evaluate:(event,ctx)=>{if(!event.toolName.startsWith("gk_"))return;const r=slot.tryGetRuntime();const grant=typeof event.params.grant==="string"?r?.store.getGrant(event.params.grant):null;if(r&&grant&&ctx.agentId&&ctx.sessionKey&&r.store.authorizeGrant(grant,ctx.agentId,ctx.sessionKey,cell())&&(grant.audience==="shared"||!r.store.observers(ctx.sessionKey).length))return;r?.audit.write({ts:new Date().toISOString(),cell:cell(),...(ctx.agentId?{agentId:ctx.agentId}:{}),...(ctx.sessionKey?{sessionKey:ctx.sessionKey}:{}),kind:"tool",title:"Capability policy denied call",decision:"deny",ok:false});return{block:true,blockReason:"No such grant."};}};}
  registerGatekeeperTools(api:OpenClawPluginApi):void{for(const d of this.catalog.tools)api.registerTool({name:d.name,label:d.name,description:d.description,parameters:d.parameters,execute:async(id,p)=>toolResult(await this.exec(id,d.name,p as Record<string,unknown>))});}
  private async exec(id:string,tool:string,params:Record<string,unknown>){const r=this.runtime(),s=r.stash.get(id);r.stash.delete(id);if(!s||s.expiresAt<Date.now()||!s.session||!s.queue||s.tool!==tool||s.paramsJson!==JSON.stringify(params)||!s.grant||!r.store.authorizeGrant(s.grant,s.agentId,s.sessionKey,cell())||(s.grant.audience==="owner-only"&&r.store.observers(s.sessionKey).length))throw new Error("Operation denied.");r.inflight.set(id,s);try{const approved=r.store.consumeToolApproval(id,tool,params);return await s.session.call(tool,params,{agentId:s.agentId,sessionKey:s.sessionKey,...(s.runId?{runId:s.runId}:{}),toolCallId:id,queue:s.queue,observers:r.store.observers(s.sessionKey),...(approved?{actionApproval:{toolCallId:id,tool,params:structuredClone(params)}}:{})});}catch{throw new Error("Operation denied.");}}
  async onBeforeAgentRun(e:HookEvent<"before_agent_run">,ctx:HookCtx<"before_agent_run">){if(this.config().maintenance)return{outcome:"block"as const,reason:"maintenance",message:"OpenClaw OS is being maintained."};if(ctx.sessionKey&&e.senderId&&!e.senderIsOwner){const r=this.runtime(),observers=new Set(r.store.observers(ctx.sessionKey));observers.add(e.senderId);r.store.setObservers(ctx.sessionKey,[...observers]);}if(!e.senderIsOwner||!this.operator(ctx.channel,e.senderId))return;for(const url of urls(e.prompt))await this.introduce(ctx.agentId??"",ctx.sessionKey??"",url,e.senderId!,"operator").catch(()=>{});}
  async onBeforePromptBuild(_e:HookEvent<"before_prompt_build">,ctx:HookCtx<"before_prompt_build">){const r=slot.tryGetRuntime();if(!r||!ctx.agentId||!ctx.sessionKey)return{toolsAllow:["os_request_access","os_list_grants"]};const sessionKey=ctx.sessionKey;const grants=r.store.listGrants(ctx.agentId).filter(g=>r.store.authorizeGrant(g,ctx.agentId!,sessionKey,cell())&&(g.scope==="agent"||g.scope===`session:${sessionKey}`)&&(g.audience==="shared"||!r.store.observers(sessionKey).length));const allowed=new Set(["os_request_access","os_list_grants"]);for(const g of grants)for(const t of r.registry.entries.get(g.vendor)?.tools??[])if(t.resourceType===g.resourceType)allowed.add(t.name);const rows=grants.slice(0,100).map(g=>`${g.handle} ${g.vendor}/${g.resourceType}${g.title?` ${g.title}`:""}`);const notes=r.notes.get(sessionKey)??[];r.notes.delete(sessionKey);const context=[...notes,rows.length?`Available grants:\n${rows.join("\n")}`:""].filter(Boolean).join("\n").slice(0,8192);return{toolsAllow:[...allowed],...(context?{appendContext:context}:{})};}
  async onBeforeToolCall(e:HookEvent<"before_tool_call">,ctx:HookCtx<"before_tool_call">){if(!e.toolName.startsWith("gk_")&&!e.toolName.startsWith("os_"))return;const id=e.toolCallId;if(!id||!ctx.agentId||!ctx.sessionKey)return{block:true,blockReason:"Missing call identity."};const r=this.runtime();for(const [key,value]of r.stash)if(value.expiresAt<Date.now())r.stash.delete(key);const base={agentId:ctx.agentId,sessionKey:ctx.sessionKey,...(ctx.runId?{runId:ctx.runId}:{}),expiresAt:Date.now()+1_800_000,startedAt:Date.now()};if(e.toolName.startsWith("os_")){r.stash.set(id,{...base,tool:e.toolName,paramsJson:JSON.stringify(e.params)});return{};}try{const params=e.params as Record<string,unknown>;if(typeof params.grant!=="string")throw new Error();const resolved=await this.resolveGrant(ctx.agentId,ctx.sessionKey,params.grant);const dry=await resolved.session.call(e.toolName,params,{agentId:ctx.agentId,sessionKey:ctx.sessionKey,...(ctx.runId?{runId:ctx.runId}:{}),toolCallId:id,queue:resolved.queue,observers:r.store.observers(ctx.sessionKey),dryRun:true})as DryRunResult;r.stash.set(id,{...base,session:resolved.session,queue:resolved.queue,grant:resolved.grant,tool:e.toolName,paramsJson:JSON.stringify(params)});if(dry.kind==="action"&&dry.description.awaitDecision)return{requireApproval:{title:dry.description.title,description:dry.description.description,severity:"critical"as const,allowedDecisions:["allow-once","deny"] as Array<"allow-once"|"deny"|"allow-always">,onResolution:(decision:string)=>r.store.recordToolDecision(id,e.toolName,params,decision)}};return{};}catch{return{block:true,blockReason:"No such grant."};}}
  async onAfterToolCall(e:HookEvent<"after_tool_call">,_ctx:HookCtx<"after_tool_call">){if(!e.toolCallId)return;const r=slot.tryGetRuntime(),s=r?.inflight.get(e.toolCallId)??r?.stash.get(e.toolCallId);if(!r||!s)return;r.stash.delete(e.toolCallId);r.inflight.delete(e.toolCallId);r.audit.write({ts:new Date().toISOString(),cell:cell(),agentId:s.agentId,sessionKey:s.sessionKey,kind:"tool",...(s.grant?{vendor:s.grant.vendor,resourceType:s.grant.resourceType,handle:s.grant.handle}:{}),title:s.tool??"kernel tool",durationMs:Date.now()-s.startedAt,ok:!e.error});}
  async requestAccess(id:string,p:{url:string;reason:string}){const r=this.runtime(),s=this.consumeStash(id,"os_request_access",p);r.store.addIntroduction({agentId:s.agentId,sessionKey:s.sessionKey,url:p.url,reason:p.reason,requestedBy:"agent"});return text("Access requested; you will be told when it is granted.");}
  async listGrantsForCall(id:string){const r=this.runtime(),s=this.consumeStash(id,"os_list_grants",{});return text(JSON.stringify(r.store.listGrants(s.agentId).filter(g=>r.store.authorizeGrant(g,s.agentId,s.sessionKey,cell())&&(g.audience==="shared"||!r.store.observers(s.sessionKey).length)).map(g=>({handle:g.handle,vendor:g.vendor,type:g.resourceType,title:g.title}))));}
  private consumeStash(id:string,tool:string,params:Record<string,unknown>):CallStash{const r=this.runtime(),s=r.stash.get(id);r.stash.delete(id);if(!s||s.tool!==tool||s.expiresAt<Date.now()||s.paramsJson!==JSON.stringify(params))throw new Error("Operation denied.");r.inflight.set(id,s);return s;}
  private async introduce(agentId:string,sessionKey:string,url:string,operatorId:string,createdBy:"operator"|"agent-request",title?:string,audience:"owner-only"|"shared"="owner-only"){if(!agentId||!sessionKey)throw new Error();const r=this.runtime();for(const{entry,resource}of r.registry.resources()){if(!matches(resource.urlPattern,url))continue;const resolved=await r.registry.introduce(entry.vendor,operatorId,url);const grant=r.store.insertGrant({handle:newHandle(),agentId,cellId:cell(),vendor:entry.vendor,resourceType:resolved.resource.type,resourceKey:resolved.resourceKey,operatorId,scope:"agent",audience,status:"active",createdAt:Date.now(),createdBy,title:title??resolved.resource.title});r.audit.write({ts:new Date().toISOString(),cell:cell(),agentId,sessionKey,kind:"grant",vendor:grant.vendor,resourceType:grant.resourceType,handle:grant.handle,title:"Grant activated",decision:"active",by:operatorId,ok:true});r.notes.set(sessionKey,[...(r.notes.get(sessionKey)??[]),`You now have access to ${grant.vendor} ${grant.resourceType} as ${grant.handle}.`]);return grant;}throw new Error();}
  gatewayMethods():Array<[string,GatewayMethod]>{const wrap=<T>(schema:TSchema,scopes:readonly string[],fn:(params:T,operator:string)=>Promise<unknown>|unknown):GatewayMethod=>async o=>{try{const params=checked<T>(schema,o.params??{}),operator=operatorIdentity(o,scopes);o.respond(true,await fn(params,operator));}catch{o.respond(false,undefined,{code:"UNAUTHORIZED",message:"Operator authorization required."});}};const read=["operator.read","operator.write","operator.admin"],write=["operator.write","operator.admin"],approvals=["operator.approvals","operator.admin"];return[["os.status",wrap(EmptyParams,read,()=>this.status())],["os.grants.list",wrap<{agentId?:string}>(ListGrantsParams,read,p=>this.runtime().store.allGrants(p.agentId))],["os.grants.introduce",wrap<{agentId:string;url:string;title?:string;audience?:"owner-only"|"shared"}>(IntroduceParams,write,(p,op)=>this.introduce(p.agentId,`rpc:${p.agentId}`,p.url,op,"operator",p.title,p.audience))],["os.grants.revoke",wrap<{handle:string}>(RevokeGrantParams,write,(p,op)=>this.revoke(p.handle,op))],["os.approvals.list",wrap(EmptyParams,read,()=>this.runtime().store.listActions())],["os.approvals.apply",wrap(ApprovalDecisionParams,approvals,(p,op)=>this.decide(p,"apply",op))],["os.approvals.reject",wrap(ApprovalDecisionParams,approvals,(p,op)=>this.decide(p,"reject",op))],["os.approvals.revert",wrap(ApprovalDecisionParams,approvals,(p,op)=>this.decide(p,"revert",op))],["os.gatekeepers.list",wrap(EmptyParams,read,()=>this.runtime().registry.health())],["os.gatekeepers.connect",wrap(ConnectGatekeeperParams,write,()=>{throw new Error();})],["os.audit.query",wrap<{limit?:number}>(AuditQueryParams,read,p=>this.runtime().audit.query(p.limit))]];}
  /** Revoke authority before awaiting cleanup; no retained session may continue using it. */
  private async revoke(handle:string,operator:string){const r=this.runtime(),grant=r.store.getGrant(handle);if(!grant)throw new Error();r.store.setGrantStatus(handle,"revoked");for(const [id,call]of r.stash)if(call.grant?.handle===handle)r.stash.delete(id);for(const sessions of r.sessions.values())for(const [session,boundHandle]of sessions)if(boundHandle===handle){sessions.delete(session);await session.close().catch(()=>{});}r.audit.write({ts:new Date().toISOString(),cell:cell(),agentId:grant.agentId,kind:"grant",handle,title:"Grant revoked",decision:"revoked",by:operator,ok:true});return{revoked:true};}
  private async decide(params:unknown,verb:"apply"|"reject"|"revert",operator:string){const r=this.runtime(),ids=(params as{ids:number[]|"all"}).ids,selected=ids==="all"?r.store.listActions().map(a=>a.id):ids;for(const id of selected){const action=r.store.getAction(id);if(!action||action.status!=="pending")throw new Error();const grant=r.store.allGrants().find(g=>instanceId(g)===action.gatekeeperInstance);if(!grant)throw new Error();const gatekeeper=await r.registry.resolveResource(grant);try{if(verb==="apply")await gatekeeper.applyAction(action.actionId);else if(verb==="reject")await gatekeeper.rejectAction(action.actionId);else if(gatekeeper.revertAction)await gatekeeper.revertAction(action.actionId);else throw new Error();r.store.decideAction(id,verb==="apply"?"applied":verb==="reject"?"rejected":"reverted",operator);}catch{throw new Error();}}return{ids:selected};}
  oauthRouter(_req:IncomingMessage,res:ServerResponse):boolean{res.statusCode=404;res.end("Not found");return true;}
  startDrainer(_ctx:OpenClawPluginServiceContext):void{} stopDrainer():void{}
  async onBeforeAgentReply(_e:HookEvent<"before_agent_reply">,_ctx:HookCtx<"before_agent_reply">){return undefined;}
  async onMessageSending(e:HookEvent<"message_sending">,ctx:HookCtx<"message_sending">){for(const source of this.config().egress?.denyPatterns??[]){let re:RegExp;try{re=new RegExp(source,"iu");}catch{return{cancel:true,cancelReason:"Invalid egress policy."};}if(re.test(typeof e.content==="string"?e.content:"")){this.runtime().audit.write({ts:new Date().toISOString(),cell:cell(),...(ctx.sessionKey?{sessionKey:ctx.sessionKey}:{}),kind:"egress",title:"Outbound message blocked",decision:"deny",ok:false});return{cancel:true,cancelReason:"Outbound policy denied this message."};}}if(ctx.sessionKey)for(const id of this.runtime().store.observers(ctx.sessionKey))this.runtime().store.taintObserver(ctx.sessionKey,id);}
  async onBeforeInstall(e:HookEvent<"before_install">,_ctx:HookCtx<"before_install">){const verdict=evaluateInstall(this.config().install,e);return verdict.decision==="allow"?undefined:{block:true,blockReason:verdict.reason!};}
  async onAgentEnd(_e:HookEvent<"agent_end">,_ctx:HookCtx<"agent_end">){}
  async onSessionEnd(_e:HookEvent<"session_end">,ctx:HookCtx<"session_end">){if(!ctx.sessionKey)return;const r=slot.tryGetRuntime(),sessions=r?.sessions.get(ctx.sessionKey);if(!sessions)return;for(const session of sessions.keys())await session.close().catch(()=>{});r!.sessions.delete(ctx.sessionKey);}
  async status(){const r=this.runtime();return{cell:cell(),upstreamVersion:"2026.9.2",kernelVersion:"0.1.0",healthy:true,maintenance:this.config().maintenance===true,gatekeepers:r.registry.health(),pendingApprovals:r.store.countPending(),pendingRequests:r.store.countPendingRequests()};}
}
function toolResult(result:ToolResult|DryRunResult){if("content" in result)return{content:result.content,details:result.details??{}};return text(JSON.stringify(result));}
function checked<T>(schema:TSchema,value:unknown):T{if(!Value.Check(schema,value))throw new Error();return value as T;}
function operatorIdentity(o:GatewayMethodOptions,allowedScopes:readonly string[]):string{const c=o.client;if(!c||c.connect?.role!=="operator"||!Array.isArray(c.connect.scopes)||!c.connect.scopes.some(scope=>allowedScopes.includes(scope))||!c.connect.device?.id||c.isDeviceTokenAuth!==true)throw new Error();return c.connect.device.id;}
function cell(){return process.env.CLAWOS_CELL??"default";}function urls(v:string){return v.match(/(?:https?:\/\/|file:\/\/\/)[^\s<>"']+/gu)??[];}function matches(pattern:string,url:string){if(pattern.startsWith("file:///"))return url.startsWith("file:///");try{return new URL(url).protocol===new URL(pattern.replace(/:[a-z][a-z0-9_]*[+]?/gi,"x")).protocol;}catch{return false;}}function newHandle(){const a="0123456789abcdefghjkmnpqrstvwxyz",b=randomBytes(8);let out="grant:";for(const x of b)out+=a[x%a.length];return out;}
