import './kernel-config.mjs';
import {readFileSync,writeFileSync} from 'node:fs';
import {resolve} from 'node:path';
import {resources,tools} from '../fixtures/phase5-driver/index.mjs';
const cfg=JSON.parse(readFileSync(process.env.OPENCLAW_CONFIG_PATH,'utf8'));
cfg.plugins.allow=['clawos-kernel','gatekeeper-fs','clawos-channel-ingress'];
cfg.plugins.load.paths=['packages/clawos-kernel','test/fixtures/phase5-driver','test/fixtures/phase5-channel'].map(p=>resolve(p));
delete cfg.plugins.entries['clawos-kernel-monitor'];cfg.plugins.entries['gatekeeper-fs'].config={};
cfg.plugins.entries['clawos-channel-ingress']={enabled:true,hooks:{allowConversationAccess:true}};
cfg.plugins.entries['clawos-kernel'].config={operators:[{channel:'vmchan',senderId:'operator'}],autoApprove:['github.issue.comment'],notify:{channel:'vmchan',target:'operator'}};
cfg.commands={ownerAllowFrom:['vmchan:operator']};cfg.channels={vmchan:{enabled:true}};
cfg.agents.list.push({id:'command'},{id:'command-group'},{id:'command-forged'});
writeFileSync(process.env.OPENCLAW_CONFIG_PATH,JSON.stringify(cfg),{mode:0o600});
writeFileSync(process.env.OPENCLAW_STATE_DIR+'/os/gatekeepers.json',JSON.stringify({version:1,gatekeepers:[{pluginId:'gatekeeper-fs',vendor:'fs',apiVersion:1,root:resolve('test/fixtures/phase5-driver'),tools,resources}]}),{mode:0o600});
for(const file of ['/home/tester/phase5-effects.jsonl','/home/tester/phase5-delivery.jsonl'])writeFileSync(file,'',{mode:0o600});
